---
- name: group exist
  group:
    name: "{{user.group}}"

- name: users exist
  user:
    name: "{{user.name}}"
    state: present
    password: "{{user.password}}"
    group: "{{user.group}}"
    groups: "{{user.groups}}"

- name: ~/.ssh for users
  file:
    path: "/home/{{user.name}}/.ssh"
    state: directory
    owner: "{{user.name}}"
    group: "{{user.group}}"
    mode: 0600

- name: authorized keys is deployed
  copy:
    src: "authorized_keys_for_{{user.name}}"
    dest: "/home/{{user.name}}/.ssh/authorized_keys"
    owner: "{{user.name}}"
    group: "{{user.group}}"
    mode: 0600

- name: /etc/sudoers.d exist
  file:
    path: /etc/sudoers.d
    state: directory
    owner: "{{user.name}}"
    group: root

- name: set yum conf
  template:
    src: yum_conf
    dest: /etc/yum.conf
    owner: root
    group: wheel
    mode: 0644
