---
- name: install nginx repo
  yum:
    name: http://nginx.org/packages/rhel/6/noarch/RPMS/nginx-release-rhel-6-0.el6.ngx.noarch.rpm
    state: present

- name: install nginx
  yum:
    name: nginx
    state: present

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: set nginx conf
  template:
    src: tomcat_nginx_conf
    dest: /etc/nginx/conf.d/default.conf
  notify: restart nginx
