---
- hosts: test_docker_container
  connection: docker
  roles:
    - common
    - web
    - app
    - db
  environment:
    http_proxy: "{{http_proxy}}"
    https_proxy: "{{http_proxy}}"
    no_proxy: "{{no_proxy}}"